name: orders_metric
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3




dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  syncfusion_flutter_charts: ^27.2.4
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2
  equatable: ^2.0.7
  intl: ^0.19.0
  dartz: ^0.10.1
  dropdown_button2: ^2.3.9
  provider: ^6.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf